"""Claim reasoning and verification package."""

from financial_evidence_engine.reasoning.claim_decomposer import ClaimDecomposer
from financial_evidence_engine.reasoning.claim_verifier import ClaimVerifier
from financial_evidence_engine.reasoning.contradiction_detector import ContradictionDetector
from financial_evidence_engine.reasoning.evidence_selector import EvidenceSelector
from financial_evidence_engine.reasoning.llm_decomposition import (
    ClaimDecompositionProvider,
    DecompositionArtifactManifest,
    DecompositionCandidate,
    DecompositionComparisonExample,
    DecompositionComparisonReport,
    DecompositionSchemaError,
    DecompositionTrace,
    LiveLLMUnavailable,
    OptionalLiveLLMClaimDecomposer,
    RecordedLLMClaimDecomposer,
    RuleBasedClaimDecomposer,
    ValidatorGate,
    build_decomposition_comparison_report,
    write_decomposition_comparison_artifacts,
)
from financial_evidence_engine.reasoning.models import (
    Claim,
    ClaimVerificationResult,
    EvidenceReference,
    Subclaim,
    SubclaimVerification,
    ValidatorCheck,
    Verdict,
)
from financial_evidence_engine.reasoning.narrative_causal import (
    ClaimType,
    NarrativeCausalArtifactManifest,
    NarrativeCausalMemo,
    NarrativeCausalReport,
    NarrativeCausalTask,
    NarrativeCausalTaskSet,
    NarrativeCausalVerificationResult,
    NarrativeCausalVerifier,
    NarrativeEvidenceFinding,
    NarrativeOverclaimExample,
    PartialVerdict,
    build_narrative_causal_memo,
    build_narrative_causal_report,
    build_narrative_causal_task_set,
    write_narrative_causal_artifacts,
)

__all__ = [
    "Claim",
    "ClaimDecompositionProvider",
    "ClaimDecomposer",
    "ClaimType",
    "ClaimVerificationResult",
    "ClaimVerifier",
    "ContradictionDetector",
    "DecompositionArtifactManifest",
    "DecompositionCandidate",
    "DecompositionComparisonExample",
    "DecompositionComparisonReport",
    "DecompositionSchemaError",
    "DecompositionTrace",
    "EvidenceReference",
    "EvidenceSelector",
    "LiveLLMUnavailable",
    "NarrativeCausalArtifactManifest",
    "NarrativeCausalMemo",
    "NarrativeCausalReport",
    "NarrativeCausalTask",
    "NarrativeCausalTaskSet",
    "NarrativeCausalVerificationResult",
    "NarrativeCausalVerifier",
    "NarrativeEvidenceFinding",
    "NarrativeOverclaimExample",
    "OptionalLiveLLMClaimDecomposer",
    "PartialVerdict",
    "RecordedLLMClaimDecomposer",
    "RuleBasedClaimDecomposer",
    "Subclaim",
    "SubclaimVerification",
    "ValidatorGate",
    "ValidatorCheck",
    "Verdict",
    "build_decomposition_comparison_report",
    "build_narrative_causal_memo",
    "build_narrative_causal_report",
    "build_narrative_causal_task_set",
    "write_decomposition_comparison_artifacts",
    "write_narrative_causal_artifacts",
]
