"""Evidence retrieval package."""

from .embeddings import (
    DeterministicTokenEmbeddingProvider,
    EMBEDDING_METHOD_NOTES,
    EmbeddingBackendUnavailable,
    EmbeddingEvidenceRetriever,
    EmbeddingHybridEvidenceRetriever,
    EmbeddingIndex,
    EmbeddingIndexManifest,
    EmbeddingProvider,
    EmbeddingRetrievalEvaluationResult,
    LocalSentenceTransformerProvider,
    MetadataBoostReranker,
    OpenAIEmbeddingProvider,
    Reranker,
    run_embedding_retrieval_evaluation,
)
from .real_baselines import (
    BM25EvidenceRetriever,
    DenseEvidenceRetriever,
    GraphEvidenceRetriever,
    HybridEvidenceRetriever,
    REAL_RETRIEVAL_METHODS,
    RealRetrievalEvaluationResult,
    RetrievalCorpus,
    RetrievalCorpusDocument,
    RetrievalFailureCase,
    RetrievalResult,
    build_retrieval_corpus,
    run_real_retrieval_evaluation,
)
from .raw_corpus import (
    ChunkIndexManifest,
    ChunkProvenance,
    CorpusVersionManifest,
    DocumentChunk,
    RawCorpusBuilder,
    RawFinancialCorpus,
    build_raw_financial_corpus,
)

__all__ = [
    "BM25EvidenceRetriever",
    "ChunkIndexManifest",
    "ChunkProvenance",
    "CorpusVersionManifest",
    "DenseEvidenceRetriever",
    "DeterministicTokenEmbeddingProvider",
    "EMBEDDING_METHOD_NOTES",
    "DocumentChunk",
    "EmbeddingBackendUnavailable",
    "EmbeddingEvidenceRetriever",
    "EmbeddingHybridEvidenceRetriever",
    "EmbeddingIndex",
    "EmbeddingIndexManifest",
    "EmbeddingProvider",
    "EmbeddingRetrievalEvaluationResult",
    "GraphEvidenceRetriever",
    "HybridEvidenceRetriever",
    "LocalSentenceTransformerProvider",
    "MetadataBoostReranker",
    "OpenAIEmbeddingProvider",
    "REAL_RETRIEVAL_METHODS",
    "RawCorpusBuilder",
    "RawFinancialCorpus",
    "RealRetrievalEvaluationResult",
    "RetrievalCorpus",
    "RetrievalCorpusDocument",
    "RetrievalFailureCase",
    "RetrievalResult",
    "Reranker",
    "build_raw_financial_corpus",
    "build_retrieval_corpus",
    "run_embedding_retrieval_evaluation",
    "run_real_retrieval_evaluation",
]
